# Generated by Django 4.2 on 2024-09-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=3, unique=True, verbose_name="Código"),
                ),
                ("descripcion", models.CharField(max_length=50, verbose_name="Descripción")),
            ],
            options={
                "verbose_name_plural": "Departamentos",
            },
        ),
    ]