# Generated by Django 4.2 on 2024-09-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nivelRuta", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nivelruta",
            options={"verbose_name_plural": "Niveles de Ruta"},
        ),
    ]
