# Generated by Django 4.2 on 2024-09-11 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("camara", "0001_initial"),
        ("ubicacion", "0001_initial"),
        ("rutaCritica", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camara",
            name="rutaCritica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rutaCritica.rutacritica",
                verbose_name="RutaCritica",
            ),
        ),
        migrations.AddField(
            model_name="camara",
            name="ubicacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ubicacion.ubicacion",
                verbose_name="Ubicación",
            ),
        ),
    ]
