# Generated by Django 4.2 on 2024-09-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rutaCritica", "0002_alter_rutacritica_options_and_more"),
        ("camara", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camara",
            options={"verbose_name_plural": "Cámaras"},
        ),
        migrations.AlterField(
            model_name="camara",
            name="recording_End",
            field=models.DateTimeField(verbose_name="Recording End"),
        ),
        migrations.AlterField(
            model_name="camara",
            name="recording_Start",
            field=models.DateTimeField(verbose_name="Recording Start"),
        ),
        migrations.AlterField(
            model_name="camara",
            name="rutaCritica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rutaCritica.rutacritica",
                verbose_name="Ruta Crítica",
            ),
        ),
    ]
