# Generated by Django 4.2 on 2024-09-11 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Denuncia", "0001_initial"),
        ("animal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleDenuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=5, unique=True, verbose_name="Código"),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="animal.animal",
                        verbose_name="Animal",
                    ),
                ),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Denuncia.denuncia",
                        verbose_name="Denuncia",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Camaras",
            },
        ),
    ]
