# Generated by Django 4.2 on 2024-09-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detalleDenuncia", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detalledenuncia",
            options={"verbose_name_plural": "Detalles de Denuncia"},
        ),
    ]
