# Generated by Django 4.2 on 2024-09-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=5, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=60, verbose_name="Nombre")),
                (
                    "direccion",
                    models.CharField(max_length=1000, verbose_name="Dirección"),
                ),
            ],
            options={
                "verbose_name_plural": "TiposDenuncia",
            },
        ),
    ]
