# Generated by Django 4.2 on 2024-09-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=5, unique=True, verbose_name="Código"),
                ),
                (
                    "descripcion_persona",
                    models.CharField(
                        max_length=1000, verbose_name="DescripciónPersona"
                    ),
                ),
                (
                    "descripcion_hechos",
                    models.CharField(max_length=1000, verbose_name="DescripciónHechos"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=1000, verbose_name="Dirección"),
                ),
                ("zona", models.CharField(max_length=8, verbose_name="Zona")),
                ("fecha", models.DateTimeField(verbose_name="Fecha")),
            ],
            options={
                "verbose_name_plural": "Denuncias",
            },
        ),
    ]
