# Generated by Django 4.2 on 2024-09-11 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Denuncia", "0001_initial"),
        ("rutaCritica", "0001_initial"),
        ("tipoDenuncia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="denuncia",
            name="rutaCritica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rutaCritica.rutacritica",
                verbose_name="RutaCritica",
            ),
        ),
        migrations.AddField(
            model_name="denuncia",
            name="tipoDenuncia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tipoDenuncia.tipodenuncia",
                verbose_name="TipoDenuncia",
            ),
        ),
    ]
