# Generated by Django 4.2 on 2024-09-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rutaCritica", "0002_alter_rutacritica_options_and_more"),
        ("tipoDenuncia", "0002_alter_tipodenuncia_options"),
        ("Denuncia", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="descripcion_hechos",
            field=models.CharField(
                max_length=1000, verbose_name="Descripción de los hechos"
            ),
        ),
        migrations.AlterField(
            model_name="denuncia",
            name="descripcion_persona",
            field=models.CharField(
                max_length=1000, verbose_name="Descripción de persona involucrada"
            ),
        ),
        migrations.AlterField(
            model_name="denuncia",
            name="rutaCritica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rutaCritica.rutacritica",
                verbose_name="Ruta Crítica",
            ),
        ),
        migrations.AlterField(
            model_name="denuncia",
            name="tipoDenuncia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tipoDenuncia.tipodenuncia",
                verbose_name="Tipo de Denuncia",
            ),
        ),
    ]
