# Generated by Django 4.2 on 2024-09-11 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=3, unique=True, verbose_name="Código"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=50, verbose_name="Descripción"),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="departamento.departamento",
                        verbose_name="Departamento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Municipios",
            },
        ),
    ]
